"use client";

import { useEffect, useState } from "react";

type Lang="en"|"ru"|"es"|"zh";
type Section={id:string;title:string;body:string;points?:string[]};

const copy:Record<Lang,{title:string;intro:string;updated:string;sections:Section[]}>= {
  en:{title:"Fantasy Guide",intro:"A practical guide to building five-emblem banners, reading player projections and accounting for Main Event opportunity.",updated:"Main Event edition · updated after the Group Stage",sections:[
    {id:"start",title:"Quick start",body:"Set the five emblems you actually own on each banner, choose one shared Prefix and Suffix, then compare the best roster with the alternatives. Only the eight active Main Event teams are ranked."},
    {id:"roster",title:"Roster and five emblems",body:"A roster contains one Core pair, one Mid player and one Support pair. Core and Support values already represent two same-team players. Main Event banners have five slots; the first three carry over from the Group Stage."},
    {id:"score",title:"What the projected score means",body:"The ranking estimates performance per match from a 1,601-match player sample across 13 Tier 1 events. It is not a prediction of total tournament points. Title odds and expected maps are shown separately so team opportunity does not silently distort player quality."},
    {id:"tiers",title:"Tiers and traits",body:"Tier I–V adds 10%, 30%, 60%, 100% or 150% to that emblem. Traits are then applied multiplicatively.",points:["Fractal: +60% to itself when all five tiers differ.","Benevolent: +20% to adjacent emblems.","Vampiric: +50% to itself and −10% to adjacent emblems.","Unique: +30% when it is the banner's only Unique emblem.","Friendly: +50% to each Friendly emblem when at least three are present."]},
    {id:"titles",title:"Prefixes and Suffixes",body:"A Prefix is shared by the entire roster. Its expected bonus uses each player's historical trigger frequency; pair frequency is the simple average of both players. The 109-map TI draft block adds tournament context. Suffixes depend on future map events, so their displayed score is an illustrative conditional scenario, not guaranteed match points."},
    {id:"potential",title:"Stars, title chance and maps",body:"A badge such as ★ 43% | 11.1 means a 43% model chance to win the title and 11.1 expected maps remaining. The 2+, 3+ and 4+ values are chances to play at least that many series. These figures help compare tournament upside but do not alter the per-match ranking."},
    {id:"rerolls",title:"Reroll priorities",body:"Prioritize a strong role-specific stat before tier alone. Avoid rerolling a banner just because one percentage is lower: include player history, trait activation, adjacency and the risk of losing already strong emblems."},
    {id:"predictions",title:"Main Event predictions",body:"The Predictions page contains the complete eight-team double-elimination bracket. Choose Balanced or TI-only, then click winners in order. Downstream opponents, match probabilities and expected Compendium points update automatically."},
    {id:"pool",title:"Prediction point pool",body:"Points depend on the total number of correct bracket picks, not which match was correct. The official scale runs from 120 points for one correct pick to 12,000 for all 14."},
    {id:"saving",title:"Saving your setup",body:"Banner emblems, Prefix and Suffix are stored locally in this browser. Reloading or closing the page keeps the setup; clearing browser storage or using another device does not."},
    {id:"data",title:"Data and freshness",body:"Player projections use the dedicated 1,601-match Fantasy sample. The broader project analysis covers 8,000+ matches. Bracket estimates use 20,000 simulations. Draft-prefix context covers 109 TI Group Stage maps."},
    {id:"limits",title:"Known limitations",body:"Lotus events are approximate in public match data. Prefixes use historical hero-group frequency. Suffixes occur on individual maps but are displayed as simplified conditional scenarios. Team probabilities are model estimates, not bookmaker odds."}
  ]},
  ru:{title:"Гайд по Fantasy",intro:"Практическое руководство по пяти эмблемам, прогнозам игроков и турнирному потенциалу Main Event.",updated:"Версия Main Event · обновлено после группового этапа",sections:[
    {id:"start",title:"Быстрый старт",body:"Укажите пять эмблем, которые есть у вас на каждом знамени, выберите общий префикс и суффикс, затем сравните лучший состав с альтернативами. В рейтинге участвуют только восемь активных команд Main Event."},
    {id:"roster",title:"Состав и пять эмблем",body:"Состав включает пару Core, одного Mid и пару Support. Значения Core и Support уже относятся к двум игрокам одной команды. В Main Event на знамени пять слотов; первые три переносятся с группового этапа."},
    {id:"score",title:"Что означает прогнозный счёт",body:"Рейтинг оценивает результат за матч по выборке из 1 601 матча на 13 турнирах Tier 1. Это не прогноз итоговых очков за весь турнир. Шанс на титул и ожидаемые карты показаны отдельно, чтобы количество игр не искажало качество игрока."},
    {id:"tiers",title:"Разряды и свойства",body:"Разряды I–V добавляют эмблеме 10%, 30%, 60%, 100% или 150%. После этого свойства применяются мультипликативно.",points:["Фрактальная: +60% к себе при пяти разных разрядах.","Благотворная: +20% соседним эмблемам.","Вампирическая: +50% к себе и −10% соседним.","Уникальная: +30%, если она единственная Unique на знамени.","Дружелюбная: +50% каждой Friendly при наличии минимум трёх."]},
    {id:"titles",title:"Префиксы и суффиксы",body:"Префикс общий для всего состава. Ожидаемый бонус использует историческую частоту срабатывания игрока; для пары берётся среднее двух игроков. Блок по 109 картам TI добавляет контекст текущих драфтов. Суффиксы зависят от будущих событий карты, поэтому показанный счёт — условный сценарий, а не гарантированные очки матча."},
    {id:"potential",title:"Звёзды, шанс на титул и карты",body:"Бейдж ★ 43% | 11,1 означает 43% шанса модели на титул и 11,1 ожидаемой карты впереди. Значения 2+, 3+ и 4+ показывают шанс сыграть минимум столько серий. Они помогают оценить потенциал турнира, но не меняют рейтинг за матч."},
    {id:"rerolls",title:"Что роллить",body:"Сначала ищите сильную характеристику для роли, а не просто высокий разряд. Не реролльте знамя только из-за одного низкого процента: учитывайте историю игрока, активацию свойства, соседство и риск потерять уже хорошие эмблемы."},
    {id:"predictions",title:"Прогнозы Main Event",body:"На странице прогнозов находится полная double-elimination сетка из восьми команд. Выберите сбалансированную модель или только TI, затем последовательно отмечайте победителей. Следующие пары, шансы матчей и ожидаемые очки Компендиума пересчитываются автоматически."},
    {id:"pool",title:"Шкала очков прогнозов",body:"Очки зависят от общего количества верных прогнозов, а не от конкретного матча. Официальная шкала начинается со 120 очков за одно совпадение и заканчивается 12 000 за все 14."},
    {id:"saving",title:"Сохранение настроек",body:"Эмблемы, префикс и суффикс сохраняются локально в этом браузере. Закрытие или перезагрузка страницы их не сбрасывает; очистка данных браузера или другое устройство — сбрасывает."},
    {id:"data",title:"Данные и актуальность",body:"Прогнозы игроков используют отдельную Fantasy-выборку из 1 601 матча. Общая аналитическая база проекта — более 8 000 матчей. Сетка оценивается на 20 000 симуляций. Контекст префиксов охватывает 109 карт группового этапа TI."},
    {id:"limits",title:"Ограничения",body:"События с лотосами приблизительны в публичных данных. Префиксы используют историческую частоту групп героев. Суффиксы срабатывают на отдельных картах, но показаны упрощёнными сценариями. Шансы команд — оценка модели, а не букмекерские коэффициенты."}
  ]},
  es:{title:"Guía de Fantasy",intro:"Guía práctica para estandartes de cinco emblemas, proyecciones y potencial del Evento Principal.",updated:"Edición del Evento Principal · actualizada tras la fase de grupos",sections:[
    {id:"start",title:"Inicio rápido",body:"Configura los cinco emblemas reales de cada estandarte, elige un Prefijo y Sufijo común y compara la mejor alineación con las alternativas. Solo se clasifican los ocho equipos activos."},{id:"roster",title:"Alineación y cinco emblemas",body:"La alineación tiene una pareja Core, un Mid y una pareja Support. Core y Support ya representan dos jugadores del mismo equipo. En el Evento Principal hay cinco espacios."},{id:"score",title:"Qué significa la puntuación",body:"La clasificación estima rendimiento por partido con una muestra de 1.601 partidos y 13 eventos Tier 1; no son puntos totales del torneo. Las probabilidades y mapas se muestran por separado."},{id:"tiers",title:"Niveles y propiedades",body:"Los niveles I–V añaden 10%, 30%, 60%, 100% o 150%. Las propiedades se aplican después de forma multiplicativa.",points:["Fractal: +60% con cinco niveles diferentes.","Benévola: +20% a los emblemas adyacentes.","Vampírica: +50% a sí misma y −10% a los adyacentes.","Única: +30% si es la única del estandarte.","Amistosa: +50% con al menos tres Amistosas."]},{id:"titles",title:"Prefijos y Sufijos",body:"El Prefijo es común para toda la alineación y usa la frecuencia histórica de cada jugador. El bloque de 109 mapas añade contexto de drafts. Los Sufijos son escenarios condicionales, no puntos garantizados."},{id:"potential",title:"Estrellas, título y mapas",body:"★ 43% | 11,1 significa 43% de opción al título y 11,1 mapas esperados. 2+, 3+ y 4+ son probabilidades de jugar al menos esas series y no cambian la clasificación por partido."},{id:"rerolls",title:"Prioridad de rerolls",body:"Prioriza estadísticas fuertes para el rol antes que el nivel por sí solo. Considera historial, activación, adyacencia y el riesgo de perder buenos emblemas."},{id:"predictions",title:"Predicciones del Evento Principal",body:"Elige el modelo Equilibrado o Solo TI y marca ganadores en el cuadro de doble eliminación. Rivales, probabilidades y puntos esperados se actualizan automáticamente."},{id:"pool",title:"Puntos de predicción",body:"Los puntos dependen del total de aciertos: 120 por uno y 12.000 por los 14."},{id:"saving",title:"Guardar configuración",body:"Emblemas, Prefijo y Sufijo se guardan localmente en este navegador."},{id:"data",title:"Datos y actualización",body:"Muestra Fantasy: 1.601 partidos. Base general: 8.000+. Simulación del cuadro: 20.000 ejecuciones. Prefijos: 109 mapas de la fase de grupos."},{id:"limits",title:"Limitaciones",body:"Los lotos son aproximados, los Prefijos usan frecuencias históricas y los Sufijos son escenarios simplificados. Las probabilidades no son cuotas de apuestas."}
  ]},
  zh:{title:"Fantasy 指南",intro:"五徽章旗帜、选手预测与主赛事机会的实用说明。",updated:"主赛事版本 · 小组赛后更新",sections:[
    {id:"start",title:"快速开始",body:"设置每面旗帜实际拥有的五枚徽章，选择全阵容共用的前缀和后缀，再比较最佳阵容与候选。排名仅包含八支主赛事战队。"},{id:"roster",title:"阵容与五枚徽章",body:"阵容包含一对核心位、一名中单和一对辅助。核心与辅助数值已代表同队两名选手。主赛事旗帜有五个槽位。"},{id:"score",title:"预测分数含义",body:"排名根据 13 项 Tier 1 赛事、1,601 场比赛的样本估算每场表现，并非整个赛事总分。冠军概率和预计地图数单独显示。"},{id:"tiers",title:"等级与特性",body:"I–V 级分别增加 10%、30%、60%、100% 和 150%，随后以乘法应用特性。",points:["分形：五个等级各不相同时自身 +60%。","仁慈：相邻徽章 +20%。","吸血：自身 +50%，相邻徽章 −10%。","独特：旗帜上唯一独特徽章时 +30%。","友好：至少三枚友好徽章时各自 +50%。"]},{id:"titles",title:"前缀与后缀",body:"前缀由全阵容共用，并使用选手历史触发频率；109 张 TI 地图提供当前 BP 环境。后缀依赖未来单局事件，因此显示的是条件场景，不是保证得分。"},{id:"potential",title:"星标、冠军概率与地图",body:"★ 43% | 11.1 表示模型冠军概率 43%、预计剩余 11.1 张地图。2+、3+、4+ 表示至少参加相应系列赛数量的概率，不改变每场排名。"},{id:"rerolls",title:"重掷优先级",body:"先看位置适配的数据，再看等级。还要考虑选手历史、特性触发、相邻效果以及失去已有优质徽章的风险。"},{id:"predictions",title:"主赛事预测",body:"选择综合模型或仅 TI 模型，按顺序点击双败淘汰赛胜者；后续对阵、胜率和预期积分会自动更新。"},{id:"pool",title:"预测积分",body:"积分取决于总命中数：命中 1 场得 120 分，14 场全中得 12,000 分。"},{id:"saving",title:"保存设置",body:"徽章、前缀和后缀保存在当前浏览器本地；清除浏览器数据或更换设备后不会保留。"},{id:"data",title:"数据与更新",body:"Fantasy 样本：1,601 场；项目总数据：8,000+ 场；对阵模拟：20,000 次；前缀环境：小组赛 109 张地图。"},{id:"limits",title:"已知限制",body:"莲花数据为近似值；前缀使用历史频率；后缀为简化条件场景。战队概率是模型估算，并非博彩赔率。"}
  ]}
};

function readLang():Lang{const value=window.localStorage.getItem("site-language") as Lang|null;return value&&copy[value]?value:"en";}
export default function GuideContent(){const[language,setLanguage]=useState<Lang>("en");useEffect(()=>{setLanguage(readLang());const onChange=(event:Event)=>{const next=(event as CustomEvent<{language?:Lang}>).detail?.language;setLanguage(next&&copy[next]?next:readLang());};window.addEventListener("site-language-change",onChange);return()=>window.removeEventListener("site-language-change",onChange);},[]);const t=copy[language];return <main className="site-shell guide-page"><div className="section-nav-wrap"><nav className="section-nav" aria-label="Guide navigation">{t.sections.map(section=><a key={section.id} href={`#${section.id}`}>{section.title}</a>)}</nav></div><section className="guide-hero"><span className="eyebrow">THE INTERNATIONAL 2026</span><h1>{t.title}</h1><p>{t.intro}</p><small>{t.updated}</small></section><section className="guide-grid">{t.sections.map((section,index)=><article className="guide-card" id={section.id} key={section.id}><span>{String(index+1).padStart(2,"0")}</span><h2>{section.title}</h2><p>{section.body}</p>{section.points&&<ul>{section.points.map(point=><li key={point}>{point}</li>)}</ul>}</article>)}</section></main>;}
